export const PRODCT_LIST_REQUEST = 'PRODCT_LIST_REQUEST';
export const PRODCT_LIST_SUCCESS = 'PRODCT_LIST_SUCCESS';
export const PRODCT_LIST_FAIL = 'PRODCT_LIST_FAIL';
export const PRODCT_DETAILS_REQUEST = 'PRODCT_DETAILS_REQUEST';
export const PRODCT_DETAILS_SUCCESS = 'PRODCT_DETAILS_SUCCESS';
export const PRODCT_DETAILS_FAIL = 'PRODCT_DETAILS_FAIL';